### ISSUE TITLE
Light grey areas

### ISSUE THREAD

**Issue by addeps3** [adamaltmejd/covid#1]
Hello. 

There is some confusion in discussion groups as to what the light grey areas are meant to represent. 
Do I understand this correctly; it this is an *estimate*, basically a hypothetical _guess_ on how many deaths will occur during that day?

**Comment by adamaltmejd** [comment]
Hey! Light grey areas are estimates based on average reporting delay from the days up to one week ago. So its not really a prediction as much as a hint at "if delays are as large as they have been before, how much more deaths would we see for these days". One could expect delays to grow both smaller and larger. On the one hand, Tegnell has said that they are trying to shorten delays. On the other, if more people are dying it seems likely that delays could increase simple because there is more deaths to register.
