### ISSUE TITLE
Average delay on mortality report day

### ISSUE THREAD

**Issue by alexanderkjeldaas** [adamaltmejd/covid#2]
It would be useful to see whether statistics on how the average delay in reporting changes over time.

- The average delay in reporting for a day
- Maybe the gradient for a linear(?) fit between (x, y) = (delayed days, number of reported cases) for the different days.  The gradient could tell us how things change over time.

**Comment by adamaltmejd** [comment]
Thats a really nice idea, but maybe for a separate graph. If I have time I'll make something like that during the weekend!

**Comment by morberg** [comment]
I took a look at this this weekend, but am not sure how to properly calculate the average lag. I ended up multiplying `n_diff` with `days_since_publication` for each row. Then adding these numbers for each date and dividing by the total number of rows per day ending up with:

<img width="534" alt="image" src="https://user-images.githubusercontent.com/956034/80369473-a0a31f80-888e-11ea-850f-793cab05c9ce.png">

Not sure how useful it is or how wrong my approach is.

**Comment by adamaltmejd** [comment]
Hey! Thanks, thats an interesting approach. I've been working on one here: https://raw.githubusercontent.com/adamaltmejd/covid/lag_plot/docs/lag_trend_sweden_latest.png

Would love to hear your thoughts. Still want to add some more information though.

**Comment by morberg** [comment]
Using reported date instead of death date on the x-axis is much better. I'm not sure on using delay on the y-axis with your layout, but I might just need some time to adjust to the idea.

An alternative approach might be to use cases on the x-axis:

<img width="873" alt="image" src="https://user-images.githubusercontent.com/956034/80374541-18754800-8897-11ea-8ce5-53a481c4b312.png">

**Comment by adamaltmejd** [comment]
I started with exactly that layout, but thought it took to much focus from the delay itself. Its really hard cause one wants to separate the trend in delay from the trend in actual deaths. (and in absolute terms, depending on how you measure it, delay will increase mechanically with actual number of deaths).

**Comment by morberg** [comment]
Agreed, the trend is really difficult to get right. I tried displaying delay as a histogram instead. It kinda works to get an idea on delay in reporting, but not for trend analysis of course.
<img width="897" alt="image" src="https://user-images.githubusercontent.com/956034/80406243-0958bf00-88c4-11ea-9051-779ba8f4b6c1.png">

When you look at it faceted by day of week (null values removed) you might gain some more insights.
<img width="749" alt="image" src="https://user-images.githubusercontent.com/956034/80407271-aa944500-88c5-11ea-99e0-5b9fe7ac9c04.png">

**Comment by morberg** [comment]
This plots the average lag for each publication day [as before](https://github.com/adamaltmejd/covid/issues/2#issuecomment-619935722) but by publication date instead of actual death date. The line is a simple 4 day rolling mean (not weighted by number of reported deaths).

<img width="757" alt="image" src="https://user-images.githubusercontent.com/956034/80463564-b53bf200-8938-11ea-8892-0d7964e1ec7a.png">

**Comment by adamaltmejd** [comment]
Thanks for your ideas! Added the WIP to the website now with a 90% percentile line inspired by what you did above @morberg. Gonna work some more on it tonight i think.

**Comment by morberg** [comment]
Clever to use a percentile for the trendline. It gives a good idea on how the lag is evolving and excludes outliers. Nice job on both this and your original graph.
