### ISSUE TITLE
False plateau in forecast

### ISSUE THREAD

**Issue by davgussnavgus** [adamaltmejd/covid#24]
In the current scenario with decreasing numbers of death your forecast is constantly overestimating the numbers pretty severely (~a factor of 2). Its a bit funny since it gives a false impression of a plateau just as FHMs numbers did when the numbers were increasing,

**Comment by adamaltmejd** [comment]
The model is conserevative and simple by construction, since it is just the historical average lag. If you want to read a more serious attempt at accurately nowcasting the number of deaths, see our working paper here: https://arxiv.org/abs/2006.06840. I might implement the model from thee paper on the website at some point when I have time, but it wont be for a couple of weeks.
