### ISSUE TITLE
Cumulative graph

### ISSUE THREAD

**Issue by hallenberg** [adamaltmejd/covid#6]
I think it could be illustrative to see the cumulative numbers in another graph to get a feel for the total and how that's developing.

**Comment by Jesper-Karlsson** [comment]
To add to the above commenter, it would be nice to have a graph that makes it easier to follow where each reporting day has been added in history, i.e. one color for each day instead of grouping them in 1,2,3-4, days lag. See below example:
![image](https://user-images.githubusercontent.com/64261275/80217956-ca670700-8640-11ea-9439-ec04e8276cc0.png)

**Comment by adamaltmejd** [comment]
Thats a really nice alternative! I decided to go with bar plots because I don't want to focus too much on the latest few days where everything is really uncertain. They way you plotted it takes focus away from the middle IMO. Although it is easier to follow reporting lag. Introduced grouping when the number of days just started to be overwhelming.

I am working on some other graphs that focus on the reporting delay. Would really appreciate feedback on those once done :).
